# Generated by Django 3.2.15 on 2022-08-27 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo2app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinations',
            old_name='image',
            new_name='img',
        ),
    ]
